# Generated by Django 6.0.6 on 2026-06-23 16:46

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TastingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', django_countries.fields.CountryField(max_length=2)),
                ('roast_level', models.CharField(choices=[('dark', 'DARK'), ('medium', 'MEDIUM'), ('light', 'LIGHT'), ('ultra-light', 'ULTRA-LIGHT')], default='medium', max_length=11)),
                ('roaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.roaster')),
                ('tasting_notes', models.ManyToManyField(to='coffeeapp.tastingnote')),
            ],
        ),
    ]
