# Generated by Django 6.0.6 on 2026-06-23 17:34

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='roast_date',
            field=models.DateField(default=datetime.date.today, verbose_name='roast date'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='roast_level',
            field=models.CharField(choices=[('dark', 'Dark'), ('medium', 'Medium'), ('light', 'Light'), ('ultra-light', 'Ultra-light')], default='medium', max_length=11),
        ),
    ]
