# Generated by Django 6.0.6 on 2026-06-24 13:39

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0002_coffee_date_added_coffee_roast_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='origin',
        ),
        migrations.AddField(
            model_name='coffee',
            name='origin',
            field=models.ManyToManyField(to='coffeeapp.country'),
        ),
    ]
