# Generated by Django 6.0.6 on 2026-06-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0003_country_remove_coffee_origin_coffee_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='country',
        ),
    ]
