# Generated by Django 6.0.6 on 2026-06-24 13:43

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0004_rename_name_country_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, unique=True),
        ),
    ]
