# Generated by Django 6.0.6 on 2026-06-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0005_alter_country_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tastingnote',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
