# Generated by Django 6.0.6 on 2026-06-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0006_alter_tastingnote_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
