# Generated by Django 6.0.6 on 2026-06-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0007_alter_country_country_alter_roaster_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
    ]
